# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''   
    set laststatus=2
    let g:airline_theme = 'deus'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'wakatime/vim-wakatime'
